template: testify
formatter: goimports
force-file-write: true
packages:
  github.com/edocsss/agent-whiteboard/internal/cli:
    config:
      dir: internal/testutil
      pkgname: testutil
    interfaces:
      Client:
        config:
          filename: mock_client.go
          structname: MockClient
  github.com/edocsss/agent-whiteboard/internal/app:
    config:
      dir: internal/testutil
      pkgname: testutil
    interfaces:
      Readiness:
        config:
          filename: mock_readiness.go
          structname: MockReadiness
  github.com/edocsss/agent-whiteboard/internal/common:
    config:
      dir: internal/testutil
      pkgname: testutil
    interfaces:
      Clock:
        config:
          filename: mock_clock.go
          structname: MockClock
      IDGenerator:
        config:
          filename: mock_id_generator.go
          structname: MockIDGenerator
  github.com/edocsss/agent-whiteboard/internal/whiteboard:
    config:
      dir: internal/testutil
      pkgname: testutil
    interfaces:
      Operations:
        config:
          filename: mock_whiteboard_operations.go
          structname: MockWhiteboardOperations
      Store:
        config:
          filename: mock_whiteboard_store.go
          structname: MockWhiteboardStore
  github.com/edocsss/agent-whiteboard/internal/image:
    config:
      dir: internal/testutil
      pkgname: testutil
    interfaces:
      Operations:
        config:
          filename: mock_image_operations.go
          structname: MockImageOperations
      Store:
        config:
          filename: mock_image_store.go
          structname: MockImageStore
