// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package testutil

import (
	"context"

	"github.com/edocsss/agent-whiteboard/internal/image"
	mock "github.com/stretchr/testify/mock"
)

// NewMockImageOperations creates a new instance of MockImageOperations. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockImageOperations(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockImageOperations {
	mock := &MockImageOperations{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockImageOperations is an autogenerated mock type for the Operations type
type MockImageOperations struct {
	mock.Mock
}

type MockImageOperations_Expecter struct {
	mock *mock.Mock
}

func (_m *MockImageOperations) EXPECT() *MockImageOperations_Expecter {
	return &MockImageOperations_Expecter{mock: &_m.Mock}
}

// CreateImages provides a mock function for the type MockImageOperations
func (_mock *MockImageOperations) CreateImages(context1 context.Context, createInput image.CreateInput) ([]image.Result, error) {
	ret := _mock.Called(context1, createInput)

	if len(ret) == 0 {
		panic("no return value specified for CreateImages")
	}

	var r0 []image.Result
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, image.CreateInput) ([]image.Result, error)); ok {
		return returnFunc(context1, createInput)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, image.CreateInput) []image.Result); ok {
		r0 = returnFunc(context1, createInput)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]image.Result)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, image.CreateInput) error); ok {
		r1 = returnFunc(context1, createInput)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockImageOperations_CreateImages_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateImages'
type MockImageOperations_CreateImages_Call struct {
	*mock.Call
}

// CreateImages is a helper method to define mock.On call
//   - context1 context.Context
//   - createInput image.CreateInput
func (_e *MockImageOperations_Expecter) CreateImages(context1 any, createInput any) *MockImageOperations_CreateImages_Call {
	return &MockImageOperations_CreateImages_Call{Call: _e.mock.On("CreateImages", context1, createInput)}
}

func (_c *MockImageOperations_CreateImages_Call) Run(run func(context1 context.Context, createInput image.CreateInput)) *MockImageOperations_CreateImages_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 image.CreateInput
		if args[1] != nil {
			arg1 = args[1].(image.CreateInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockImageOperations_CreateImages_Call) Return(results []image.Result, err error) *MockImageOperations_CreateImages_Call {
	_c.Call.Return(results, err)
	return _c
}

func (_c *MockImageOperations_CreateImages_Call) RunAndReturn(run func(context1 context.Context, createInput image.CreateInput) ([]image.Result, error)) *MockImageOperations_CreateImages_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockImageOperations
func (_mock *MockImageOperations) Delete(context1 context.Context, s string) error {
	ret := _mock.Called(context1, s)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(context1, s)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockImageOperations_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockImageOperations_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
func (_e *MockImageOperations_Expecter) Delete(context1 any, s any) *MockImageOperations_Delete_Call {
	return &MockImageOperations_Delete_Call{Call: _e.mock.On("Delete", context1, s)}
}

func (_c *MockImageOperations_Delete_Call) Run(run func(context1 context.Context, s string)) *MockImageOperations_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockImageOperations_Delete_Call) Return(err error) *MockImageOperations_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockImageOperations_Delete_Call) RunAndReturn(run func(context1 context.Context, s string) error) *MockImageOperations_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockImageOperations
func (_mock *MockImageOperations) Get(context1 context.Context, s string) (image.Image, error) {
	ret := _mock.Called(context1, s)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 image.Image
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (image.Image, error)); ok {
		return returnFunc(context1, s)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) image.Image); ok {
		r0 = returnFunc(context1, s)
	} else {
		r0 = ret.Get(0).(image.Image)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(context1, s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockImageOperations_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockImageOperations_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
func (_e *MockImageOperations_Expecter) Get(context1 any, s any) *MockImageOperations_Get_Call {
	return &MockImageOperations_Get_Call{Call: _e.mock.On("Get", context1, s)}
}

func (_c *MockImageOperations_Get_Call) Run(run func(context1 context.Context, s string)) *MockImageOperations_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockImageOperations_Get_Call) Return(image1 image.Image, err error) *MockImageOperations_Get_Call {
	_c.Call.Return(image1, err)
	return _c
}

func (_c *MockImageOperations_Get_Call) RunAndReturn(run func(context1 context.Context, s string) (image.Image, error)) *MockImageOperations_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockImageOperations
func (_mock *MockImageOperations) Update(context1 context.Context, updateInput image.UpdateInput) (image.Result, error) {
	ret := _mock.Called(context1, updateInput)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 image.Result
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, image.UpdateInput) (image.Result, error)); ok {
		return returnFunc(context1, updateInput)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, image.UpdateInput) image.Result); ok {
		r0 = returnFunc(context1, updateInput)
	} else {
		r0 = ret.Get(0).(image.Result)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, image.UpdateInput) error); ok {
		r1 = returnFunc(context1, updateInput)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockImageOperations_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockImageOperations_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - context1 context.Context
//   - updateInput image.UpdateInput
func (_e *MockImageOperations_Expecter) Update(context1 any, updateInput any) *MockImageOperations_Update_Call {
	return &MockImageOperations_Update_Call{Call: _e.mock.On("Update", context1, updateInput)}
}

func (_c *MockImageOperations_Update_Call) Run(run func(context1 context.Context, updateInput image.UpdateInput)) *MockImageOperations_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 image.UpdateInput
		if args[1] != nil {
			arg1 = args[1].(image.UpdateInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockImageOperations_Update_Call) Return(result image.Result, err error) *MockImageOperations_Update_Call {
	_c.Call.Return(result, err)
	return _c
}

func (_c *MockImageOperations_Update_Call) RunAndReturn(run func(context1 context.Context, updateInput image.UpdateInput) (image.Result, error)) *MockImageOperations_Update_Call {
	_c.Call.Return(run)
	return _c
}
