// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package testutil

import (
	"context"

	"github.com/edocsss/agent-whiteboard/internal/whiteboard"
	mock "github.com/stretchr/testify/mock"
)

// NewMockWhiteboardStore creates a new instance of MockWhiteboardStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWhiteboardStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWhiteboardStore {
	mock := &MockWhiteboardStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockWhiteboardStore is an autogenerated mock type for the Store type
type MockWhiteboardStore struct {
	mock.Mock
}

type MockWhiteboardStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWhiteboardStore) EXPECT() *MockWhiteboardStore_Expecter {
	return &MockWhiteboardStore_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type MockWhiteboardStore
func (_mock *MockWhiteboardStore) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockWhiteboardStore_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockWhiteboardStore_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockWhiteboardStore_Expecter) Close() *MockWhiteboardStore_Close_Call {
	return &MockWhiteboardStore_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockWhiteboardStore_Close_Call) Run(run func()) *MockWhiteboardStore_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockWhiteboardStore_Close_Call) Return(err error) *MockWhiteboardStore_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockWhiteboardStore_Close_Call) RunAndReturn(run func() error) *MockWhiteboardStore_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type MockWhiteboardStore
func (_mock *MockWhiteboardStore) Create(context1 context.Context, whiteboard1 whiteboard.Whiteboard) error {
	ret := _mock.Called(context1, whiteboard1)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, whiteboard.Whiteboard) error); ok {
		r0 = returnFunc(context1, whiteboard1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockWhiteboardStore_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockWhiteboardStore_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - context1 context.Context
//   - whiteboard1 whiteboard.Whiteboard
func (_e *MockWhiteboardStore_Expecter) Create(context1 any, whiteboard1 any) *MockWhiteboardStore_Create_Call {
	return &MockWhiteboardStore_Create_Call{Call: _e.mock.On("Create", context1, whiteboard1)}
}

func (_c *MockWhiteboardStore_Create_Call) Run(run func(context1 context.Context, whiteboard1 whiteboard.Whiteboard)) *MockWhiteboardStore_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 whiteboard.Whiteboard
		if args[1] != nil {
			arg1 = args[1].(whiteboard.Whiteboard)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockWhiteboardStore_Create_Call) Return(err error) *MockWhiteboardStore_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockWhiteboardStore_Create_Call) RunAndReturn(run func(context1 context.Context, whiteboard1 whiteboard.Whiteboard) error) *MockWhiteboardStore_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockWhiteboardStore
func (_mock *MockWhiteboardStore) Delete(context1 context.Context, s string) error {
	ret := _mock.Called(context1, s)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(context1, s)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockWhiteboardStore_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockWhiteboardStore_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
func (_e *MockWhiteboardStore_Expecter) Delete(context1 any, s any) *MockWhiteboardStore_Delete_Call {
	return &MockWhiteboardStore_Delete_Call{Call: _e.mock.On("Delete", context1, s)}
}

func (_c *MockWhiteboardStore_Delete_Call) Run(run func(context1 context.Context, s string)) *MockWhiteboardStore_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockWhiteboardStore_Delete_Call) Return(err error) *MockWhiteboardStore_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockWhiteboardStore_Delete_Call) RunAndReturn(run func(context1 context.Context, s string) error) *MockWhiteboardStore_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockWhiteboardStore
func (_mock *MockWhiteboardStore) Get(context1 context.Context, s string) (whiteboard.Whiteboard, error) {
	ret := _mock.Called(context1, s)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 whiteboard.Whiteboard
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (whiteboard.Whiteboard, error)); ok {
		return returnFunc(context1, s)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) whiteboard.Whiteboard); ok {
		r0 = returnFunc(context1, s)
	} else {
		r0 = ret.Get(0).(whiteboard.Whiteboard)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(context1, s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWhiteboardStore_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockWhiteboardStore_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
func (_e *MockWhiteboardStore_Expecter) Get(context1 any, s any) *MockWhiteboardStore_Get_Call {
	return &MockWhiteboardStore_Get_Call{Call: _e.mock.On("Get", context1, s)}
}

func (_c *MockWhiteboardStore_Get_Call) Run(run func(context1 context.Context, s string)) *MockWhiteboardStore_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockWhiteboardStore_Get_Call) Return(whiteboard1 whiteboard.Whiteboard, err error) *MockWhiteboardStore_Get_Call {
	_c.Call.Return(whiteboard1, err)
	return _c
}

func (_c *MockWhiteboardStore_Get_Call) RunAndReturn(run func(context1 context.Context, s string) (whiteboard.Whiteboard, error)) *MockWhiteboardStore_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Ready provides a mock function for the type MockWhiteboardStore
func (_mock *MockWhiteboardStore) Ready(context1 context.Context) error {
	ret := _mock.Called(context1)

	if len(ret) == 0 {
		panic("no return value specified for Ready")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(context1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockWhiteboardStore_Ready_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ready'
type MockWhiteboardStore_Ready_Call struct {
	*mock.Call
}

// Ready is a helper method to define mock.On call
//   - context1 context.Context
func (_e *MockWhiteboardStore_Expecter) Ready(context1 any) *MockWhiteboardStore_Ready_Call {
	return &MockWhiteboardStore_Ready_Call{Call: _e.mock.On("Ready", context1)}
}

func (_c *MockWhiteboardStore_Ready_Call) Run(run func(context1 context.Context)) *MockWhiteboardStore_Ready_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockWhiteboardStore_Ready_Call) Return(err error) *MockWhiteboardStore_Ready_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockWhiteboardStore_Ready_Call) RunAndReturn(run func(context1 context.Context) error) *MockWhiteboardStore_Ready_Call {
	_c.Call.Return(run)
	return _c
}

// Replace provides a mock function for the type MockWhiteboardStore
func (_mock *MockWhiteboardStore) Replace(context1 context.Context, whiteboard1 whiteboard.Whiteboard) error {
	ret := _mock.Called(context1, whiteboard1)

	if len(ret) == 0 {
		panic("no return value specified for Replace")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, whiteboard.Whiteboard) error); ok {
		r0 = returnFunc(context1, whiteboard1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockWhiteboardStore_Replace_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Replace'
type MockWhiteboardStore_Replace_Call struct {
	*mock.Call
}

// Replace is a helper method to define mock.On call
//   - context1 context.Context
//   - whiteboard1 whiteboard.Whiteboard
func (_e *MockWhiteboardStore_Expecter) Replace(context1 any, whiteboard1 any) *MockWhiteboardStore_Replace_Call {
	return &MockWhiteboardStore_Replace_Call{Call: _e.mock.On("Replace", context1, whiteboard1)}
}

func (_c *MockWhiteboardStore_Replace_Call) Run(run func(context1 context.Context, whiteboard1 whiteboard.Whiteboard)) *MockWhiteboardStore_Replace_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 whiteboard.Whiteboard
		if args[1] != nil {
			arg1 = args[1].(whiteboard.Whiteboard)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockWhiteboardStore_Replace_Call) Return(err error) *MockWhiteboardStore_Replace_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockWhiteboardStore_Replace_Call) RunAndReturn(run func(context1 context.Context, whiteboard1 whiteboard.Whiteboard) error) *MockWhiteboardStore_Replace_Call {
	_c.Call.Return(run)
	return _c
}
